server:
  name: go-sql-hexagonal-architecture-sample
  port: 8090

sql:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password: Bbc@148562
  database: local

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

client:
  log: true
  timeout: 5000000000
  request: request
  response: response
  duration: duration
  status: status

server_url: http://localhost:8080
